const ORDER_SAVE_REQUEST = "ORDER_SAVE_REQUEST";
const ORDER_SAVE_SUCESS = "ORDER_SAVE_SUCESS ";
const ORDER_SAVE_FAIL = "ODER_SAVE_FAIL";

const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
const ORDER_DETAIL_SUCESS = "ORDER_DETAIL_SUCESS";
const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
const ORDER_DELETE_SUCESS = "ORDER_DELETE_SUCESS";
const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";

const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
const ORDER_LIST_SUCESS = "ORDER_LIST_SUCESS";
const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

const MY_ORDER_LIST_REQUEST = "MY_ORDER_LIST_REQUEST";
const MY_ORDER_LIST_SUCESS = "MY_ORDER_LIST_SUCESS";
const MY_ORDER_LIST_FAIL = "MY_ORDER_LIST_FAIL";

const PAY_REQUEST = "PAY_REQUEST";
const PAY_SUCESS = "PAY_SUCESS";
const PAY_FAIL = "PAY_FAIL";


export { 
    ORDER_SAVE_FAIL, 
    ORDER_SAVE_REQUEST, 
    ORDER_SAVE_SUCESS,
    ORDER_DELETE_SUCESS,
    ORDER_DELETE_FAIL,
    ORDER_DELETE_REQUEST,
    ORDER_DETAIL_FAIL,
    ORDER_DETAIL_REQUEST,
    ORDER_DETAIL_SUCESS,
    MY_ORDER_LIST_FAIL,
    MY_ORDER_LIST_REQUEST,
    MY_ORDER_LIST_SUCESS,
    PAY_FAIL,
    PAY_REQUEST,
    PAY_SUCESS,
    ORDER_LIST_FAIL,
    ORDER_LIST_REQUEST,
    ORDER_LIST_SUCESS
};
