// Aqui irá ficar todas as constantes
// Elas serão usadas para quando criar actions eu não correr risco de digitar informações erradas
const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
const PRODUCT_LIST_SUCESS = "PRODUCT_LIST_SUCESS";
const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCESS = "PRODUCT_DETAILS_SUCESS";
const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

const PRODUCT_REGISTER_REQUEST = "PRODUCT_REGISTER_REQUEST";
const PRODUCT_REGISTER_SUCESS = "PRODUCT_REGISTER_SUCESS";
const PRODUCT_REGISTER_FAIL = "PRODUCT_REGISTER_FAIL";

const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
const PRODUCT_DELETE_SUCESS = "PRODUCT_DELETE_SUCESS";
const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

const PRODUCT_REVIEW_REQUEST = "PRODUCT_REVIEW_REQUEST";
const PRODUCT_REVIEW_SUCESS = "PRODUCT_REVIEW_SUCESS";
const PRODUCT_REVIEW_FAIL = "PRODUCT_REVIEW_FAIL";
const PRODUCT_REVIEW_RESET = "PRODUCT_REVIEW_RESET";


export {
  PRODUCT_LIST_FAIL,
  PRODUCT_LIST_SUCESS,
  PRODUCT_LIST_REQUEST,
  PRODUCT_DETAILS_REQUEST,
  PRODUCT_DETAILS_SUCESS,
  PRODUCT_DETAILS_FAIL,
  PRODUCT_REGISTER_FAIL,
  PRODUCT_REGISTER_REQUEST,
  PRODUCT_REGISTER_SUCESS,
  PRODUCT_DELETE_FAIL,
  PRODUCT_DELETE_SUCESS,
  PRODUCT_DELETE_REQUEST,
  PRODUCT_REVIEW_SUCESS,
  PRODUCT_REVIEW_REQUEST,
  PRODUCT_REVIEW_FAIL,
  PRODUCT_REVIEW_RESET
};
