const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_REQUEST_SUCESS = "LOGIN_REQUEST_SUCESS ";
const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";
const REGISTER_REQUEST = "REGISTER_REQUEST";
const REGISTER_REQUEST_SUCESS = "REGISTER_REQUEST_SUCESS ";
const REGISTER_REQUEST_ERROR = "REGISTER_REQUEST_ERROR";
const LOGOUT_SUCESS = "LOGOUT_SUCESS";
const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_SUCESS = "UPDATE_USER_SUCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";




export {
    LOGIN_REQUEST,
    LOGIN_REQUEST_SUCESS ,
    LOGIN_REQUEST_ERROR,
    REGISTER_REQUEST,
    REGISTER_REQUEST_ERROR,
    REGISTER_REQUEST_SUCESS,
    LOGOUT_SUCESS,
    UPDATE_USER_ERROR,
    UPDATE_USER_REQUEST,
    UPDATE_USER_SUCESS
};
